services:
  # ---------------------- 前端服务 ----------------------
  frontend:
    build: ./frontend
    volumes:
      # - /宿主机路径:/容器内路径:选项(权限)
      - ./data:/data
    ports:
      - "80:80"
    depends_on:
      - service-api
      - service-analysis
    networks:
      - app-network

  # ---------------------- 后端服务 ----------------------
  service-api:
    build: ./backend/service-api
    environment:
      - DB_HOST=db
      - DB_API_NAME=${DB_API_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - db
    networks:
      - app-network

  service-analysis:
    build: ./backend/service-analysis
    environment:
      - DB_HOST=db
      - DB_ANALYSIS_NAME=${DB_ANALYSIS_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ANALYSIS_BASE_URL=${ANALYSIS_BASE_URL}
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

  # ---------------------- 共享服务 ----------------------
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_API_NAME},${DB_ANALYSIS_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
  rabbitmq-data: